-- Loaded automatically by `supabase db reset`. Demo rows intentionally have no owner;
-- production RLS keeps them invisible to authenticated tenants.
with seed(name,organization,investor_type,introducer,event_name) as (values
('Elena Park','Northstar Family Office','Family Office','Marcus Chen','Frontier AI Summit'),('Sofia Kovacs','Veridian Capital','Family Office','Lina Ho','Milken Global Conference'),('Mateo Alvarez','Cedar Ridge Partners','Family Office','Priya Shah','Palm Beach Allocators Dinner'),('Grace Liu','Juniper Grove Holdings','Family Office','Daniel Cho','SF Family Office Forum'),('Owen Whitaker','Whitaker Legacy Partners','Family Office','Sarah Lin','YPO Capital Night'),('Nadia Rahman','Crescent Harbor Capital','Family Office','Amir Qureshi','Emerging Manager Circle'),('Lucas Moretti','Vela Family Partners','Family Office','Gianna Russo','SuperReturn Berlin'),('Camille Dubois','Maison Arc Capital','Family Office','Theo Martin','Paris Private Markets Salon'),('Ethan Rosen','Stonebridge Family Partners','Family Office','Maya Feldman','Institutional LP Dinner'),('Mei Tanaka','Horizon Grove','Family Office','Kenji Sato','Tokyo Allocators Forum'),
('Aisha Patel','Crescent Peak Partners','Fund of Funds','David Mercer','Women in Alternatives'),('Thomas Reid','Harborlight Funds','Fund of Funds','Megan Ortiz','SuperReturn North America'),('Isabelle Laurent','Montclair Alternatives','Fund of Funds','Camille Dubois','IPEM Paris'),('Jonas Berg','Nordhaven Partners','Fund of Funds','Sofia Kovacs','Nordic Private Capital Forum'),('Rachel Kim','Waypoint Venture Partners','Fund of Funds','Elena Park','NVCA LP Summit'),('Samuel Okoro','Baobab Capital Partners','Fund of Funds','James Okafor','Africa Investment Forum'),('Clara Stein','Linden Fund Partners','Fund of Funds','Jonas Berg','Berlin LP Roundtable'),('Victor Santos','Atlas Multi-Manager','Fund of Funds','Mateo Alvarez','LatAm Private Capital Summit'),('Leila Haddad','Mosaic Alternatives','Fund of Funds','Nadia Rahman','MENA Allocators Forum'),('Andrew Collins','Westlake Portfolio Partners','Fund of Funds','Thomas Reid','PartnerConnect West'),
('Brooke Sullivan','Sullivan Wealth Advisory','RIA','Owen Whitaker','RIA Edge Conference'),('Noah Bennett','Beacon Crest Advisors','RIA','Andrew Collins','Schwab IMPACT'),('Priyanka Rao','Meridian Private Wealth','RIA','Aisha Patel','Future Proof Festival'),('Gabriel Torres','Torres Capital Advisory','RIA','Victor Santos','CAIS Alternative Investment Summit'),('Hannah Weiss','Oak & Field Wealth','RIA','Ethan Rosen','Institutional Investor Forum'),('Marcus Lee','Summitline Advisors','RIA','Rachel Kim','Venture Capital Journal LP Day'),('Olivia Grant','Grant Harbor Wealth','RIA','Brooke Sullivan','TIGER 21 Gathering'),('Ravi Menon','Blue Banyan Advisory','RIA','Priyanka Rao','iConnections Global Alts'),('Claire Beaumont','Beaumont Private Wealth','RIA','Isabelle Laurent','Monaco Wealth Forum'),('Julian Foster','Northgate Advisory','RIA','Noah Bennett','Future of Private Markets'),
('Maya Feldman','Independent Angel','Angel Investor','Ethan Rosen','AI Founders Dinner'),('Daniel Cho','Independent Angel','Angel Investor','Grace Liu','Developer Tools Salon'),('Priya Shah','Operator Angel Collective','Angel Investor','Aisha Patel','SaaS Leaders Retreat'),('Kenji Sato','Independent Angel','Angel Investor','Mei Tanaka','Tokyo Founder Night'),('Amir Qureshi','Qureshi Angel Network','Angel Investor','Nadia Rahman','Global Tech Majlis'),('Gianna Russo','Independent Angel','Angel Investor','Lucas Moretti','Italian Tech Week'),('Theo Martin','Founders Circle Europe','Angel Investor','Camille Dubois','Station F Demo Day'),('Sarah Lin','Independent Angel','Angel Investor','Rachel Kim','All Raise LP Dinner'),('Megan Ortiz','Operator Capital Network','Angel Investor','Thomas Reid','Latinas in VC Summit'),('Liam Osei','Independent Angel','Angel Investor','Samuel Okoro','Accra Tech Week'),
('James Okafor','Catalyst Foundation','Foundation','Samuel Okoro','Mission Investors Exchange'),('David Mercer','Hawthorne Endowment','Foundation','Sarah Lin','Endowment CIO Roundtable'),('Fatima Zahra','Al Noor Foundation','Foundation','Leila Haddad','Global Impact Forum'),('Emily Carter','Brightwell Foundation','Foundation','Olivia Grant','SOCAP'),('Nathan Greene','Greene Family Foundation','Foundation','Brooke Sullivan','Impact Capital Managers'),('Helena Fischer','Neue Zukunft Stiftung','Foundation','Clara Stein','Berlin Impact Week'),('Ana Costa','Horizonte Foundation','Foundation','Victor Santos','GIIN Investor Forum'),('Michael Chen','Forward Science Foundation','Foundation','Daniel Cho','Deep Tech Alliance'),('Zuri Ndlovu','Ubuntu Futures Foundation','Foundation','Liam Osei','AVCA Conference'),('Laura Bennett','Common Ground Foundation','Foundation','Emily Carter','Skoll World Forum')
), numbered as (select *,row_number() over() n from seed)
insert into public.lp_profiles(name,organization,investor_type,heat,interests,concerns,introduction_source,introduction_event,last_contact_date,next_follow_up,next_action,meeting_notes,commitment,commitment_amount,commitment_status)
select name,organization,investor_type::public.lp_type,(case when n%5=0 then 'Cold' when n%3=0 then 'Hot' else 'Warm' end)::public.relationship_heat,
case investor_type when 'Family Office' then array['AI infrastructure','enterprise software','seed funds'] when 'Fund of Funds' then array['emerging managers','venture funds','portfolio construction'] when 'RIA' then array['private markets access','B2B software','co-investments'] when 'Angel Investor' then array['developer tools','applied AI','founder-led funds'] else array['mission alignment','responsible AI','economic mobility'] end,
array[(array['Fund I attribution','emerging manager risk','portfolio concentration','fee load','liquidity horizon','team bandwidth'])[((n-1)%6)+1]],introducer,event_name,current_date-(n%35),current_date+((n%18)-5),
(array['Send data room access','Share founder references','Schedule partner meeting','Provide attribution analysis','Send portfolio construction memo'])[((n-1)%5)+1],
array['Discussed fund strategy, differentiation, and team edge. LP asked detailed questions and requested a clear next step.','Follow-up meeting showed increased engagement. Reviewed pipeline, ownership targets, and reference process.'],
case when n%4=0 then 'Verbal indication pending diligence' when n%7=0 then 'Requested side-letter review' else null end,case when n%4=0 then 250000*(1+(n%5)) else null end,case when n%4=0 then 'indicated' when n%7=0 then 'reviewing' else null end from numbered;

insert into public.memories(lp_id,kind,content,metadata,occurred_at)
select id,'meeting',meeting_notes[1],jsonb_build_object('source','demo seed','event',introduction_event),last_contact_date::timestamptz from public.lp_profiles where owner_id is null;
insert into public.action_items(lp_id,title,due_date,status)
select id,next_action,next_follow_up,case when next_follow_up<current_date then 'overdue' else 'open' end from public.lp_profiles where owner_id is null;

-- Five additional records per allocator segment bring the demo to 75 LPs.
insert into public.lp_profiles(name,organization,investor_type,heat,interests,concerns,introduction_source,introduction_event,last_contact_date,next_follow_up,next_action,meeting_notes,commitment,commitment_amount,commitment_status) values
('Adrian Cole','Colebridge Investments','Family Office','Warm',array['AI infrastructure','Seed funds'],array['Fund I attribution'],'Maya Feldman','ZAS Founder Dinner',current_date-4,current_date+3,'Send track record analysis',array['Requested track record detail before a partner discussion.'],'Potential commitment',750000,'evaluating'),
('Mina Shah','Lotus Gate Capital','Family Office','Hot',array['Applied AI','Vertical SaaS'],array['Portfolio concentration'],'Priya Shah','Emerging Manager Circle',current_date-2,current_date+1,'Schedule partner meeting',array['Strong thesis fit and interest after the first-close update.'],'Verbal indication',500000,'indicated'),
('Frederik Holm','North Sound Holdings','Family Office','Cold',array['Developer tools','Cybersecurity'],array['Timing'],'Jonas Berg','Nordic LP Forum',current_date-28,current_date+14,'Add to quarterly updates',array['Passed for timing; requested quarterly updates.'],null,null,null),
('Chloe Bennett','Ashbury Family Partners','Family Office','Warm',array['Enterprise software'],array['Team bandwidth'],'Olivia Grant','Milken Global Conference',current_date-7,current_date+4,'Share founder references',array['Requested two founder references.'],null,null,null),
('Rafael Costa','Serra Vista Capital','Family Office','Warm',array['Fintech','Applied AI'],array['Fee load'],'Victor Santos','LatAm Private Capital Summit',current_date-8,current_date+5,'Send fund deck',array['Interested after meeting the team.'],null,null,null),
('Rebecca Moss','New Arc Fund Partners','Fund of Funds','Hot',array['Emerging managers','Seed funds'],array['Ownership targets'],'Aisha Patel','NVCA LP Summit',current_date-1,current_date+2,'Provide attribution analysis',array['Requested detailed attribution and ownership analysis.'],'Potential allocation',1000000,'evaluating'),
('Darius King','Union Square Allocators','Fund of Funds','Warm',array['Venture funds','Co-investments'],array['Portfolio construction'],'Thomas Reid','SuperReturn North America',current_date-5,current_date+3,'Share founder references',array['Requested reference calls with two founders.'],null,null,null),
('Yuki Mori','Kansai Multi-Manager','Fund of Funds','Cold',array['Emerging managers'],array['Timing'],'Mei Tanaka','Tokyo Allocators Forum',current_date-30,current_date+30,'Send first-close update',array['Passed due to current vintage pacing.'],null,null,null),
('Alice Romano','Aurelia Fund Partners','Fund of Funds','Warm',array['AI infrastructure','Venture funds'],array['Emerging manager risk'],'Gianna Russo','IPEM Paris',current_date-6,current_date+6,'Schedule diligence call',array['Interested after first close; asked for diligence meeting.'],null,null,null),
('Peter Walsh','Keystone Venture Access','Fund of Funds','Warm',array['Seed funds','Enterprise software'],array['Fund size'],'Andrew Collins','PartnerConnect West',current_date-9,current_date+2,'Send data room access',array['Requested data room and fund model.'],null,null,null),
('Natalie Brooks','Cedar Angel Syndicate','Angel Investor','Hot',array['Applied AI','Founder-led funds'],array['Fund I attribution'],'Sarah Lin','AI Founders Dinner',current_date-2,current_date+1,'Share track record',array['High conviction in the thesis; requested track record.'],'Verbal indication',250000,'indicated'),
('Arjun Mehta','Independent Angel','Angel Investor','Warm',array['Developer tools','Fintech'],array['Liquidity horizon'],'Priya Shah','SaaS Leaders Retreat',current_date-4,current_date+4,'Send fund deck',array['Requested the deck and portfolio overview.'],null,null,null),
('Eva Lindstrom','Nordic Operator Angels','Angel Investor','Cold',array['Climate tech','Applied AI'],array['Timing'],'Sofia Kovacs','Nordic Private Capital Forum',current_date-24,current_date+20,'Add to quarterly updates',array['Passed due to timing; open to future updates.'],null,null,null),
('Carlos Mendes','Independent Angel','Angel Investor','Warm',array['Enterprise software'],array['Team bandwidth'],'Rafael Costa','LatAm Founders Dinner',current_date-8,current_date+5,'Schedule follow-up',array['Asked to meet the wider partnership.'],null,null,null),
('Zoe Turner','Frontier Angels','Angel Investor','Warm',array['AI infrastructure','Cybersecurity'],array['Portfolio concentration'],'Daniel Cho','Developer Tools Salon',current_date-10,current_date+3,'Share founder references',array['Requested founder and co-investor references.'],null,null,null),
('Dana Miller','Rockwell Private Wealth','RIA','Hot',array['Private markets access','B2B software'],array['Liquidity horizon'],'Brooke Sullivan','RIA Edge Conference',current_date-1,current_date+1,'Send subscription overview',array['Interested in a $500K client allocation.'],'Potential allocation',500000,'evaluating'),
('Sebastian Cruz','Cruz Fiduciary Partners','RIA','Warm',array['Co-investments','Applied AI'],array['Fee load'],'Gabriel Torres','CAIS Summit',current_date-5,current_date+5,'Provide fee comparison',array['Requested fee and vehicle comparison.'],null,null,null),
('Irene Wu','Pacific Crest Advisory','RIA','Cold',array['B2B software'],array['Timing'],'Marcus Lee','Future Proof Festival',current_date-31,current_date+25,'Send quarterly update',array['Not allocating before Q4; requested updates.'],null,null,null),
('Neil Kapoor','Evergreen Wealth Partners','RIA','Warm',array['Seed funds','AI infrastructure'],array['Emerging manager risk'],'Ravi Menon','iConnections Global Alts',current_date-7,current_date+4,'Share institutional references',array['Requested institutional LP references.'],null,null,null),
('Monica Hayes','Hayes Capital Counsel','RIA','Warm',array['Tax-efficient vehicles','Enterprise software'],array['Fund structure'],'Noah Bennett','Schwab IMPACT',current_date-12,current_date+3,'Send structure memo',array['Asked for vehicle and tax structure detail.'],null,null,null),
('Ben Williams','Open Horizons Foundation','Foundation','Hot',array['Responsible AI','Economic mobility'],array['Mission alignment'],'James Okafor','Mission Investors Exchange',current_date-2,current_date+2,'Send impact framework',array['Strong mission fit; requested impact measurement framework.'],'Potential allocation',750000,'evaluating'),
('Sana Ali','Progressive Futures Trust','Foundation','Warm',array['Health equity','Applied AI'],array['Portfolio concentration'],'Fatima Zahra','Global Impact Forum',current_date-6,current_date+5,'Schedule investment committee prep',array['Preparing for investment committee discussion.'],null,null,null),
('Robert Fields','Fields Education Foundation','Foundation','Cold',array['Education technology'],array['Timing'],'Emily Carter','SOCAP',current_date-26,current_date+18,'Add to quarterly updates',array['Passed this cycle; requested quarterly updates.'],null,null,null),
('Maria Vega','Nexus Community Foundation','Foundation','Warm',array['Economic mobility','Fintech'],array['Fund I attribution'],'Ana Costa','GIIN Investor Forum',current_date-9,current_date+4,'Provide attribution analysis',array['Requested attribution and impact case studies.'],null,null,null),
('George Taylor','Longview Climate Foundation','Foundation','Warm',array['Climate tech','Responsible AI'],array['Mission alignment'],'Laura Bennett','Skoll World Forum',current_date-11,current_date+6,'Send portfolio mapping',array['Requested thesis-to-mission portfolio mapping.'],null,null,null);

insert into public.memories(lp_id,kind,content,metadata,occurred_at)
select p.id,'meeting',p.meeting_notes[1],jsonb_build_object('source','demo seed','event',p.introduction_event),p.last_contact_date::timestamptz from public.lp_profiles p where p.owner_id is null and not exists(select 1 from public.memories m where m.lp_id=p.id);
insert into public.action_items(lp_id,title,due_date,status)
select p.id,p.next_action,p.next_follow_up,case when p.next_follow_up<current_date then 'overdue' else 'open' end from public.lp_profiles p where p.owner_id is null and not exists(select 1 from public.action_items a where a.lp_id=p.id);
