export type Heat="Hot"|"Warm"|"Cold";
export type LPType="Family Office"|"Fund of Funds"|"Angel Investor"|"RIA"|"Foundation";
export type LP={id:string;initials:string;color:string;name:string;firm:string;type:LPType;status:Heat;strength:number;interest:string;interests:string[];last:string;next:string;due:string;source:string;event:string;concern:string;commitment:string;commitmentAmount:number;activity:string;meetings:{date:string,title:string,note:string}[]};

const groups:Record<LPType,[string,string][]>={
"Family Office":[["Elena Park","Northstar Family Office"],["Sofia Kovacs","Veridian Capital"],["Mateo Alvarez","Cedar Ridge Partners"],["Grace Liu","Juniper Grove Holdings"],["Owen Whitaker","Whitaker Legacy Partners"],["Nadia Rahman","Crescent Harbor Capital"],["Lucas Moretti","Vela Family Partners"],["Camille Dubois","Maison Arc Capital"],["Ethan Rosen","Stonebridge Family Partners"],["Mei Tanaka","Horizon Grove"],["Adrian Cole","Colebridge Investments"],["Mina Shah","Lotus Gate Capital"],["Frederik Holm","North Sound Holdings"],["Chloe Bennett","Ashbury Family Partners"],["Rafael Costa","Serra Vista Capital"]],
"Fund of Funds":[["Aisha Patel","Crescent Peak Partners"],["Thomas Reid","Harborlight Funds"],["Isabelle Laurent","Montclair Alternatives"],["Jonas Berg","Nordhaven Partners"],["Rachel Kim","Waypoint Venture Partners"],["Samuel Okoro","Baobab Capital Partners"],["Clara Stein","Linden Fund Partners"],["Victor Santos","Atlas Multi-Manager"],["Leila Haddad","Mosaic Alternatives"],["Andrew Collins","Westlake Portfolio Partners"],["Rebecca Moss","New Arc Fund Partners"],["Darius King","Union Square Allocators"],["Yuki Mori","Kansai Multi-Manager"],["Alice Romano","Aurelia Fund Partners"],["Peter Walsh","Keystone Venture Access"]],
"Angel Investor":[["Maya Feldman","Independent Angel"],["Daniel Cho","Independent Angel"],["Priya Shah","Operator Angel Collective"],["Kenji Sato","Independent Angel"],["Amir Qureshi","Qureshi Angel Network"],["Gianna Russo","Independent Angel"],["Theo Martin","Founders Circle Europe"],["Sarah Lin","Independent Angel"],["Megan Ortiz","Operator Capital Network"],["Liam Osei","Independent Angel"],["Natalie Brooks","Cedar Angel Syndicate"],["Arjun Mehta","Independent Angel"],["Eva Lindstrom","Nordic Operator Angels"],["Carlos Mendes","Independent Angel"],["Zoe Turner","Frontier Angels"]],
"RIA":[["Brooke Sullivan","Sullivan Wealth Advisory"],["Noah Bennett","Beacon Crest Advisors"],["Priyanka Rao","Meridian Private Wealth"],["Gabriel Torres","Torres Capital Advisory"],["Hannah Weiss","Oak & Field Wealth"],["Marcus Lee","Summitline Advisors"],["Olivia Grant","Grant Harbor Wealth"],["Ravi Menon","Blue Banyan Advisory"],["Claire Beaumont","Beaumont Private Wealth"],["Julian Foster","Northgate Advisory"],["Dana Miller","Rockwell Private Wealth"],["Sebastian Cruz","Cruz Fiduciary Partners"],["Irene Wu","Pacific Crest Advisory"],["Neil Kapoor","Evergreen Wealth Partners"],["Monica Hayes","Hayes Capital Counsel"]],
"Foundation":[["James Okafor","Catalyst Foundation"],["David Mercer","Hawthorne Endowment"],["Fatima Zahra","Al Noor Foundation"],["Emily Carter","Brightwell Foundation"],["Nathan Greene","Greene Family Foundation"],["Helena Fischer","Neue Zukunft Stiftung"],["Ana Costa","Horizonte Foundation"],["Michael Chen","Forward Science Foundation"],["Zuri Ndlovu","Ubuntu Futures Foundation"],["Laura Bennett","Common Ground Foundation"],["Ben Williams","Open Horizons Foundation"],["Sana Ali","Progressive Futures Trust"],["Robert Fields","Fields Education Foundation"],["Maria Vega","Nexus Community Foundation"],["George Taylor","Longview Climate Foundation"]]
};
const colors=["#3d4b72","#8e6358","#60776b","#817056","#536276","#745f78","#6d7651"];
const intros=["Marcus Chen","Sarah Lin","David Mercer","Aisha Patel","Daniel Cho","Lina Ho","Rachel Kim","Priya Shah"];
const events=["Frontier AI Summit","NVCA LP Forum","Emerging Manager Circle","Milken Global Conference","Institutional LP Dinner","SuperReturn North America"];
const concerns=["Fund I attribution","Emerging manager risk","Portfolio concentration","Team bandwidth","Fee load","Timing before first close","Liquidity horizon"];
const actions=["Send data room access","Share founder references","Provide track record analysis","Schedule partner meeting","Send first-close update","Add to quarterly updates"];
const activityOptions=["Requested the fund deck","Requested founder references","Requested detailed track record","Interested after first close","Passed due to timing","Requested quarterly updates"];
const interestSets:Record<LPType,string[][]>={
"Family Office":[["AI infrastructure","Enterprise software"],["Developer tools","Seed funds"],["Applied AI","Cybersecurity"]],
"Fund of Funds":[["Emerging managers","Venture funds"],["Portfolio construction","Seed funds"],["Co-investments","Enterprise software"]],
"Angel Investor":[["Founder-led funds","Developer tools"],["Applied AI","Future of work"],["Enterprise software","Fintech"]],
"RIA":[["Private markets access","B2B software"],["Co-investments","AI infrastructure"],["Tax-efficient vehicles","Seed funds"]],
"Foundation":[["Responsible AI","Economic mobility"],["Mission alignment","Climate tech"],["Health equity","Applied AI"]]
};

let index=0;
export const demoLPs:LP[]=Object.entries(groups).flatMap(([type,rows])=>rows.map(([name,firm],local)=>{const i=index++;const status:Heat=i%6===0?"Cold":i%3===0?"Hot":"Warm";const interests=interestSets[type as LPType][local%3];const amount=i%4===0?(250000*((i%5)+1)):0;return{id:`lp-${i+1}`,initials:name.split(" ").map(x=>x[0]).join(""),color:colors[i%colors.length],name,firm,type:type as LPType,status,strength:status==="Hot"?88-(i%8):status==="Warm"?68-(i%10):42-(i%7),interest:interests.join(", "),interests,last:i%4===0?"Yesterday":`Jun ${22-(i%15)}`,next:actions[i%actions.length],due:i%11===0?"Overdue":i%7===0?"Today":`Jun ${24+(i%7)}`,source:intros[i%intros.length],event:events[i%events.length],concern:concerns[i%concerns.length],commitment:amount?"Verbal indication · diligence pending":"No commitment yet",commitmentAmount:amount,activity:activityOptions[i%activityOptions.length],meetings:[{date:`Jun ${22-(i%15)}`,title:"Fund introduction",note:`Discussed ZAS Ventures' concentrated seed strategy. ${name.split(" ")[0]} ${activityOptions[i%activityOptions.length].toLowerCase()} and raised ${concerns[i%concerns.length].toLowerCase()}.`},{date:`May ${18-(i%9)}`,title:"Initial relationship call",note:`Introduced by ${intros[i%intros.length]} after ${events[i%events.length]}. Strong fit around ${interests[0].toLowerCase()}.`} ]}}));

demoLPs[0]={...demoLPs[0],status:"Hot",strength:92,due:"Today",commitment:"$1M verbal indication · diligence pending",commitmentAmount:1000000};
export const insights=["12 LPs need follow-up this week","3 LPs requested references","5 LPs interested after first close","2 warm introductions available","Estimated fundraising pipeline: $4.2M"];
export const activities=[{title:"Elena Park requested data room access",meta:"Northstar Family Office · 18 minutes ago",tag:"Strong intent"},{title:"David Mercer requested founder references",meta:"Hawthorne Endowment · Yesterday",tag:"Action captured"},{title:"Aisha Patel is interested after first close",meta:"Crescent Peak Partners · Jun 20",tag:"Pipeline advanced"},{title:"Sofia Kovacs passed due to timing",meta:"Veridian Capital · Jun 19",tag:"Quarterly updates"},{title:"Marcus Chen introduced Elena Park",meta:"Frontier AI Summit · Jun 18",tag:"Relationship mapped"}];
